name: Test and Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: |
          backend/yarn.lock
          yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run linting
      run: yarn lint

    - name: Run tests
      run: yarn test

    - name: Run E2E tests
      run: yarn test:e2e

    - name: Build application
      run: yarn build

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: |
          frontend/yarn.lock
          yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run linting
      run: yarn lint

    - name: Build application
      run: yarn build

  docker-build-test:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Frontend image (test)
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: marketflow-frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Backend image (test)
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: false
        tags: marketflow-backend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate test summary
      run: |
        echo "## ✅ Tests and Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🧪 Test Results" >> $GITHUB_STEP_SUMMARY
        echo "- **Backend Tests:** ✅ Passed" >> $GITHUB_STEP_SUMMARY
        echo "- **Frontend Build:** ✅ Passed" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Build:** ✅ Passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Built Images" >> $GITHUB_STEP_SUMMARY
        echo "- \`marketflow-frontend:test\`" >> $GITHUB_STEP_SUMMARY
        echo "- \`marketflow-backend:test\`" >> $GITHUB_STEP_SUMMARY
